/***********************************************************************/
/*                                                                     */
/*  FILE        :Empty.c                                               */
/*  DATE        :Mon, Jan 08, 2007                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.0).     */
/*                                                                     */
/***********************************************************************/
     
#include "qsk_bsp.h"
#include "qsk_led.h"

// prototypes

void mcu_init(void);	              

/* *******************************************************************
 Description:
 Entry:
 Returns:
 
 Notes:
 
***********************************************************************/ 

#pragma INTERRUPT Switch1Handler
#pragma INTERRUPT Switch2Handler

void InitSwitchInt(void) {
	_asm("fset i");
	ilvl0_int0ic = 1;
	ilvl1_int0ic = 0;
	ilvl2_int0ic = 0;
	pol_int0ic = 0;
	
	ilvl0_int1ic = 1;
	ilvl1_int1ic = 0;
	ilvl2_int1ic = 0;
	pol_int1ic = 0;
} 

void Switch1Handler(void) {
	pd7_2 = 1;
	pd8_0 = 1;
	p8_0 = !p8_0;
	p7_2 = !p7_2;
}

void Switch2Handler(void) {
	pd7_4 = 1;
	pd7_2 = 1;
	p7_2 = !p7_2;
	p7_4 = !p7_4;
}

void main(void)
{
	
	mcu_init();
	
	InitSwitchInt();
	
}
